# Generated by Django 4.1 on 2022-09-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_birthdate_user_currency_user_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="superhost",
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
