# Generated by Django 4.1 on 2022-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_superhost_alter_user_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="superhost",
            field=models.BooleanField(default=False),
        ),
    ]
